#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

PROJECT_ROOT="${PROJECT_ROOT:-/opt/home-sensor/server}"
MOSQUITTO_CONF_SOURCE="${PROJECT_ROOT}/config/mosquitto/home-sensor.conf"
MOSQUITTO_CONF_TARGET="/etc/mosquitto/conf.d/home-sensor.conf"
MOSQUITTO_ACL_TARGET="/etc/mosquitto/acl.d/home-sensor.acl"
MOSQUITTO_PASSWORD_FILE="/etc/mosquitto/passwd"
GATEWAY_USER="${MQTT_GATEWAY_USERNAME:-home_sensor_gateway}"
BRIDGE_USER="${MQTT_USERNAME:-home_sensor_bridge}"

usage() {
  cat <<USAGE
Usage: sudo scripts/install_mosquitto.sh [options]

Install Mosquitto and the home sensor broker configuration.

Options:
  --gateway-user USER      Gateway MQTT username. Default: home_sensor_gateway
  --bridge-user USER       Bridge MQTT username. Default: home_sensor_bridge
  -h, --help               Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gateway-user)
      GATEWAY_USER="${2:-}"
      [[ -n "${GATEWAY_USER}" ]] || die "--gateway-user requires a value"
      shift 2
      ;;
    --bridge-user)
      BRIDGE_USER="${2:-}"
      [[ -n "${BRIDGE_USER}" ]] || die "--bridge-user requires a value"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

require_linux
require_root
require_command apt-get

[[ -f "${MOSQUITTO_CONF_SOURCE}" ]] || die "Missing Mosquitto config: ${MOSQUITTO_CONF_SOURCE}"

for username in "${GATEWAY_USER}" "${BRIDGE_USER}"; do
  [[ "${username}" != *:* ]] || die "MQTT usernames must not contain ':'"
  [[ "${username}" != *[[:space:]]* ]] || die "MQTT usernames must not contain whitespace"
done

log "Installing Mosquitto broker and client utilities"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y mosquitto mosquitto-clients

log "Installing Mosquitto home sensor configuration"
install -d -m 0755 -o root -g root /etc/mosquitto/conf.d
install -d -m 0755 -o root -g root /etc/mosquitto/acl.d
install -m 0644 -o root -g root "${MOSQUITTO_CONF_SOURCE}" "${MOSQUITTO_CONF_TARGET}"
cat > "${MOSQUITTO_ACL_TARGET}" <<ACL
# Home Sensor Mosquitto ACL.
# Generated by install_mosquitto.sh.

user ${GATEWAY_USER}
topic write home/sensors/+
topic write home/air/+

user ${BRIDGE_USER}
topic read home/sensors/+
topic read home/air/+
ACL
chown root:root "${MOSQUITTO_ACL_TARGET}"
chmod 0644 "${MOSQUITTO_ACL_TARGET}"

if [[ ! -f "${MOSQUITTO_PASSWORD_FILE}" ]]; then
  warn "Mosquitto password file is not present yet: ${MOSQUITTO_PASSWORD_FILE}"
  warn "Run ${PROJECT_ROOT}/scripts/create_mqtt_users.sh before starting or restarting Mosquitto"
else
  if getent group mosquitto >/dev/null 2>&1; then
    chown root:mosquitto "${MOSQUITTO_PASSWORD_FILE}"
  else
    chown root:root "${MOSQUITTO_PASSWORD_FILE}"
  fi
  chmod 0640 "${MOSQUITTO_PASSWORD_FILE}"
fi

if command -v systemctl >/dev/null 2>&1; then
  log "Enabling Mosquitto service"
  systemctl enable mosquitto.service
  log "Mosquitto config installed. Restart after user setup with: sudo systemctl restart mosquitto.service"
else
  warn "systemctl not available; enable and restart Mosquitto manually"
fi

log "Mosquitto installation/configuration step complete"
